{% set version = "0.18.2" %}

package:
  name: xarray
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xarray/xarray-{{ version }}.tar.gz
  sha256: 5d2e72a228286fcf60f66e16876bd27629a1a70bf64822c565f16515c4d10284

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    # Drop support for python 3.6 https://github.com/pydata/xarray/pull/4720
    - python >=3.7
    - pip
    - setuptools_scm
    - wheel

  run:
    - python >=3.7
    - numpy >=1.17
    - pandas >=1.0
    # Drop support for python 3.6 https://github.com/pydata/xarray/pull/4720
    - setuptools >=40.4 # For pkg_resources
    - typing-extensions

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - pytest
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: N-D labeled arrays and datasets in Python.
  dev_url: https://github.com/pydata/xarray
  doc_url: http://xarray.pydata.org/en/stable

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
