{% set name = "xarray" %}
{% set version = "2026.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 978b6acb018770554f8fd964af4eb02f9bcc165d4085dbb7326190d92aa74bcf

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip:  true  # [py<311]

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.3
    - setuptools_scm >=8
  run:
    - python
    # numpy max cap is added here due to compatibility issue discovered by test failure (test_concat_periods)
    # with numpy>=2. Issue seems to be already known: https://github.com/pydata/xarray/issues/11189
    # this is a conservative cap. remove upper bound once fixed upstream.
    - numpy >=1.26,<2  # [py<313]
    - numpy >=1.26     # [py>=313]
    - packaging >=24.1
    - pandas >=2.2
  run_constrained:
    # accel
    - scipy >=1.13
    - numbagg >=0.8
    - numba >=0.62
    - flox >=0.9
    # io
    - netcdf4 >=1.6.0
    - h5netcdf >=1.4.0
    - zarr >=2.18
    # etc
    - sparse >=0.15
    # viz
    - cartopy >=0.23
    - matplotlib-base >=3.8

{% set deselect_tests = "" %}
# hdf5 not build with szip support
{% set deselect_tests = deselect_tests + " --deselect=test_backends.py::TestNetCDF4Data::test_compression_encoding" %}
{% set deselect_tests = deselect_tests + " --deselect=test_backends_datatree.py::TestNetCDF4DataTree::test_compression_encoding" %}

# Tests related to incompatibility with numpy >=2.0. Restore tests once constraint is no longer needed.
# due to compatibility issue with numpy>=2 (we only have packages for those versions with Python 3.13)
{% set deselect_tests = deselect_tests + " --deselect=test_dataarray.py::TestDataArray::test_curvefit_helpers" %}   # [py>=313]
{% set deselect_tests = deselect_tests + " --deselect=test_variable.py::TestIndexVariable::test_concat_periods" %}  # [py>=313]
# due to incosistent integer size 32/64-bit in numpy<2 on Windows (numpy 2 standardized integer types).
{% set deselect_tests = deselect_tests + " --deselect=test_coding_times.py::test_decode_timedelta_via_units" %}  # [py<313 and win]
{% set deselect_tests = deselect_tests + " --deselect=test_dataset.py::TestDataset::test_to_and_from_dataframe" %}  # [py<313 and win]
{% set deselect_tests = deselect_tests + " --deselect=test_datatree.py::TestRepr::test_repr_truncates_nodes" %}  # [py<313 and win]
{% set deselect_tests = deselect_tests + " --deselect=test_formatting.py::TestFormatting::test_diff_datatree_repr_equals" %}  # [py<313 and win]
{% set deselect_tests = deselect_tests + " --deselect=test_namedarray.py::test_fake_target_chunksize" %}  # [py<313 and win]

test:
  source_files:
    - conftest.py
    - pyproject.toml
  imports:
    - xarray
    - xarray.backends
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest . --pyargs xarray.tests {{ deselect_tests }} -vv -m "not (flaky or mypy or network or slow or slow_hypothesis)" -o addopts="--strict-markers --strict-config"
  requires:
    - pip
    - pytest
    - pytest-xdist
    - pytest-timeout
    - pytest-asyncio
    - pooch
    - scipy
    - netcdf4
    - pytz
    # using >=3 will cause TestDataset.test_repr to fail with: assert "<xarray.Dataset> Size: 2kB\nDimensions:...
    - pandas <3

about:
  home: https://xarray.dev
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: N-D labeled arrays and datasets in Python.
  description: |
    xarray (formerly xray) is an open source project and Python package
    that makes working with labelled multi-dimensional arrays simple,
    efficient, and fun!

    xarray introduces labels in the form of dimensions, coordinates and
    attributes on top of raw NumPy_-like arrays, which allows for a more
    intuitive, more concise, and less error-prone developer experience.
    The package includes a large and growing library of domain-agnostic functions for advanced analytics and visualization with these data structures.

    xarray was inspired by and borrows heavily from pandas_, the popular data analysis package focused on labelled tabular data.
    It is particularly tailored to working with netCDF_ files, which were the source of xarray's data model, and integrates tightly with dask_ for parallel computing.
  dev_url: https://github.com/pydata/xarray
  doc_url: https://docs.xarray.dev

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
