{% set name = "xarray" %}
{% set version = "2025.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c2b5ad7389825bd624ada5ff26b01ac54b1aae72e2fe0d724d81d40a2bf5785

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip:  True  # [py<311]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=77.0.3
    - setuptools_scm >=8
  run:
    - python
    - numpy >=1.26
    - pandas >=2.2
    - packaging >=24.1
  run_constrained:
    - scipy >=1.13
    - numbagg >=0.8
    - flox >=0.9
    - netcdf4 >=1.6.0
    - zarr >=2.18
    - sparse >=0.15
    - cartopy >=0.23

# hdf5 not build with szip support
{% set deselect_tests = "test_compression_encoding[szip]" %}

test:
  source_files:
    - conftest.py
    - pyproject.toml
  imports:
    - xarray
    - xarray.backends
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest . --pyargs xarray.tests -k "not ({{ deselect_tests }})" -v -m "not (flaky or mypy or network or slow or slow_hypothesis)" -o addopts="[--strict-markers,--strict-config]"
  requires:
    - pip
    - pytest
    - pytest-xdist
    - pytest-timeout
    - pytest-asyncio
    - pooch
    - scipy
    - netcdf4

about:
  home: https://xarray.dev
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: N-D labeled arrays and datasets in Python.
  description: |
    xarray (formerly xray) is an open source project and Python package
    that makes working with labelled multi-dimensional arrays simple,
    efficient, and fun!

    xarray introduces labels in the form of dimensions, coordinates and
    attributes on top of raw NumPy_-like arrays, which allows for a more
    intuitive, more concise, and less error-prone developer experience.
    The package includes a large and growing library of domain-agnostic functions for advanced analytics and visualization with these data structures.

    xarray was inspired by and borrows heavily from pandas_, the popular data analysis package focused on labelled tabular data.
    It is particularly tailored to working with netCDF_ files, which were the source of xarray's data model, and integrates tightly with dask_ for parallel computing.
  dev_url: https://github.com/pydata/xarray
  doc_url: https://docs.xarray.dev

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
