{% set version = "2022.11.0" %}

package:
  name: xarray
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xarray/xarray-{{ version }}.tar.gz
  sha256: 3008a302877f87a0f9043b1f01a4ad4e85b668bbdd38d488764098624632f527

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    # Drop support for python 3.6 https://github.com/pydata/xarray/pull/4720
    - python
    - pip
    - setuptools
    - setuptools_scm_git_archive
    - setuptools_scm >=3.4
    - toml
    - wheel

  run:
    - python >=3.7
    - numpy >=1.18
    - pandas >=1.1
    # Drop support for python 3.6 https://github.com/pydata/xarray/pull/4720
    - setuptools >=40.4 # For pkg_resources
    - importlib-metadata
    - typing-extensions >=3.7

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - pytest
    - python <3.10
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: N-D labeled arrays and datasets in Python.
  dev_url: https://github.com/pydata/xarray
  doc_url: http://xarray.pydata.org/en/stable

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
