travis:
  secure:
    BINSTAR_TOKEN: ks5WO2jpJaLhfb6laAKZbARVpdsUtQiyTSJAGPr2+UrCAkj1nkd+muEERQ0Eucyzzx3Evvkkc6pxVb+0QnHOZo/p5ZMjdlm5+tVxRAxg8w43TSZUZIBrILH1t9DK6GGcEQFxtXrzhl3E9pBEL/P1t8c7Nl6hoLfMCw1BTvcWO4Af/OEU6qCoS/HwZT5LZt3t39ciuTBwMyD6ZfQDITCV2RKPsu2uvkjfjBzyNXZ1QpxQP2qy4jxCaZzBVfFJXLYWJFd0QJXZLg5JgUKjsp8efESURayzYc9R1TmcnYgfZRiTE/4k1xKvcOrF0d8M0GTSYrISXy9HJDB6yy7Qe6MJEPMsUDhSXzK+LFYOctemqHYcgSYo2QrUkwlz1jYZbLt9ElRed1/chW8OuLUBguiDKsBbOmOH9XrelzENt3jyLFypVlw7K58MVdiu4mjwLsUgkkstEQELQFpfch6zLk6VrMIkLFBjAqkmpnvHOF43TkS3LJK/h79tDeQGME+C1Y9Obrh6b9jrQX9OcRp4xfRMYfUrYkjIkfsGGQH7e/3Olb/CeFviGezeSZesC5n6hXhcd5jqdxGsqKy3FKN/9il0y/9ST9YCkOZ/dI+AKQ50qXJ+1IspiGfyF7JO9FuHQfF8ZyydTVtJKaED+u0AnEE4D7q5SlhwOr4I2TfNeuWj5lM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
max_py_ver: '37'
