travis:
  secure:
    BINSTAR_TOKEN: oyiIEBTqiHl06V8Eq1V+DQ0BaqTJqPuTKfxAeZTXEMWmOsH9M/iidXqxaHbLxvdq3MpWx46OgfJw415qr1CrKK5BMszgLfm6wXjUzAjPGcbER0knE38SoYuScZC7U5zNsFGPN+AV4lbNKV9NNwBR10/5560/mOA6+IgozwhljupplHNcjtrvFfH1dfU002QanKKFHwhdGXMef2drHKYwy5ybeoDyYOFvQ9AjvICF0JEENeS+yZ6FBp47j+h5NL4R6sa+cmJ2PANZykFclalT3myvPk04hLQuZ04pYsOApVYofo4UwafYgSODdph9SqUGXS7IqGSxIWzqUMLHDL4ICLalaczZ2koinSriwnGURTYg0JI3sarPkIQAxbolCEB8+CqGM5Cmn6XeQbMz9T7BhW4VqDSMhc9AMNVEcK/NbMLstpV5VR5rS27q8vCdOhxYbQ//h4rn9R9utFxvQp5qrgj9AszuM1ZqSlCAnkQvk37+YUnXr2IvCzH/gVzbARow9E1gDwt0FrLnaHFRiHIGCMpPCq0vrz02kO/xEjgMqD9Svo9niOaQ3FcHGYd2HDP6xYKAkOps08qCq1fD0dFMPTYk478Fpk6hPxq99nq9JzcuVYDcHSe/GBT/ATOMAuRSTzaOCj800XnpF5GRNiG5TN04wgmSQWdeU5LEBDrliCs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
